# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-01-28 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Should be same as folder name', max_length=63, unique=True)),
                ('date', models.DateField()),
                ('state', models.CharField(max_length=63)),
                ('area', models.CharField(help_text='e.g. Little Bear, Denali, Sante Fe, West Coast, ...', max_length=63)),
                ('type', models.CharField(help_text='e.g. Mountaineering, Hiking, Family Vacation, Climbing, ...', max_length=63)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
