# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='test',
            field=models.ImageField(null=True, upload_to=b''),
        ),
    ]
