# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 22:21
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_trip_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='test',
        ),
        migrations.AddField(
            model_name='trip',
            name='picture',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to=b''),
        ),
    ]
