# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 22:47
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_auto_20170203_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to=b'')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='trip',
            name='id',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='picture',
        ),
        migrations.AddField(
            model_name='trip',
            name='pictures',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to=b''),
        ),
        migrations.AlterField(
            model_name='trip',
            name='name',
            field=models.CharField(help_text='Should be same as folder name', max_length=63, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='tripimages',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='trip.Trip'),
        ),
    ]
