# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 22:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0004_auto_20170203_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='pictures',
        ),
    ]
