# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0006_auto_20170203_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripimage',
            name='description',
            field=models.CharField(help_text='trip_name + pic file name', max_length=63, null=True),
        ),
    ]
